#!/usr/bin/env node
// generate-zip-map.mjs
//
// Generates the ZIP → neighborhood mapping table by joining the GeoJSON
// boundary file against the neighborhood dataset from data.ts.
//
// Usage:
//   node scripts/generate-zip-map.mjs
//
// Output:
//   - Console report of matched / unmatched ZIPs
//   - Prints the updated zipNeighborhoodMap.ts content to stdout
//     (redirect to file or copy-paste)

import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const root  = resolve(__dir, '..');

// ── Load GeoJSON ──────────────────────────────────────────────────
const geojsonPath = resolve(root, 'client/public/data/alameda_sf_tracts.geojson');
const geojson = JSON.parse(readFileSync(geojsonPath, 'utf8'));
const allZips = geojson.features.map(f => ({
  zip:  f.properties.ZIP_CODE,
  city: f.properties.PO_NAME,
  pop:  f.properties.POPULATION,
}));

// ── Neighborhood data (mirrored from data.ts) ─────────────────────
// Kept in sync manually until the project adds a JSON export of data.ts.
const neighborhoods = [
  { id: 'sobrante-park',         name: 'Sobrante Park',       city: 'Oakland',     zipCodes: ['94603'],            needScore: 8.2 },
  { id: 'east-oakland-69th',     name: 'East Oakland (69th)', city: 'Oakland',     zipCodes: ['94605', '94621'],   needScore: 5.7 },
  { id: 'west-oakland',          name: 'West Oakland',        city: 'Oakland',     zipCodes: ['94607', '94612'],   needScore: 7.9 },
  { id: 'fruitvale',             name: 'Fruitvale',           city: 'Oakland',     zipCodes: ['94601'],            needScore: 6.1 },
  { id: 'elmhurst',              name: 'Elmhurst',            city: 'Oakland',     zipCodes: ['94603', '94621'],   needScore: 5.8 },
  { id: 'south-hayward',         name: 'South Hayward',       city: 'Hayward',     zipCodes: ['94544'],            needScore: 7.6 },
  { id: 'san-antonio',           name: 'San Antonio',         city: 'Oakland',     zipCodes: ['94606'],            needScore: 5.4 },
  { id: 'seminary',              name: 'Seminary',            city: 'Oakland',     zipCodes: ['94605'],            needScore: 3.9 },
  { id: 'san-leandro-washington',name: 'Washington Manor',    city: 'San Leandro', zipCodes: ['94579'],            needScore: 5.9 },
  { id: 'fremont-area',          name: 'Fremont (Central)',   city: 'Fremont',     zipCodes: ['94538'],            needScore: 5.2 },
];

// ── Build ZIP → [neighborhood] map ────────────────────────────────
const zipMap = {};
for (const n of neighborhoods) {
  for (const zip of n.zipCodes) {
    if (!zipMap[zip]) zipMap[zip] = [];
    zipMap[zip].push({ id: n.id, needScore: n.needScore });
  }
}

// Sort each ZIP's neighborhoods by need score descending (primary = highest need)
for (const zip of Object.keys(zipMap)) {
  zipMap[zip].sort((a, b) => b.needScore - a.needScore);
}

// ── Coverage report ───────────────────────────────────────────────
console.log('\n══════════════════════════════════════════════════');
console.log('  FieldFinder · ZIP → Neighborhood Coverage Report');
console.log('══════════════════════════════════════════════════\n');

const mappedZips   = allZips.filter(z => zipMap[z.zip]);
const unmappedZips = allZips.filter(z => !zipMap[z.zip]);

console.log(`GeoJSON features:      ${allZips.length} ZIP codes`);
console.log(`Neighborhood dataset:  ${neighborhoods.length} neighborhoods`);
console.log(`Matched ZIPs:          ${mappedZips.length}`);
console.log(`Unmatched ZIPs:        ${unmappedZips.length} (rendered dimly; no sidebar data)\n`);

console.log('── Matched ──────────────────────────────────────');
for (const z of mappedZips) {
  const entries = zipMap[z.zip].map(e => `${e.id} (${e.needScore})`).join(', ');
  console.log(`  ${z.zip}  ${z.city.padEnd(15)}  →  ${entries}`);
}

console.log('\n── Unmatched (need neighborhood assignment) ──────');
for (const z of unmappedZips) {
  console.log(`  ${z.zip}  ${z.city}`);
}

// ── Neighborhood ZIPs missing from GeoJSON ────────────────────────
const geojsonZipSet = new Set(allZips.map(z => z.zip));
const missingFromGeoJson = neighborhoods.filter(n =>
  n.zipCodes.some(z => !geojsonZipSet.has(z))
);
if (missingFromGeoJson.length) {
  console.log('\n── Neighborhood ZIPs not in GeoJSON (will have no polygon) ──');
  for (const n of missingFromGeoJson) {
    const missing = n.zipCodes.filter(z => !geojsonZipSet.has(z));
    console.log(`  ${n.id}: missing ZIPs ${missing.join(', ')}`);
  }
}

// ── Generate zipNeighborhoodMap.ts content ────────────────────────
console.log('\n══════════════════════════════════════════════════');
console.log('  Generated zipNeighborhoodMap.ts content');
console.log('══════════════════════════════════════════════════\n');

const lines = [
  '// AUTO-GENERATED by scripts/generate-zip-map.mjs',
  '// Re-run after updating neighborhoods in data.ts or the GeoJSON file.',
  '',
  'export const zipToNeighborhoods: Record<string, string[]> = {',
];

for (const [zip, entries] of Object.entries(zipMap)) {
  const ids = entries.map(e => `'${e.id}'`).join(', ');
  const city = allZips.find(z => z.zip === zip)?.city ?? '';
  const comment = entries.length > 1
    ? `// ${entries.map(e => `${e.id} (${e.needScore})`).join(', ')}`
    : `// ${city}`;
  lines.push(`  '${zip}': [${ids}], ${comment}`);
}

lines.push('};', '');
lines.push("export function getPrimaryNeighborhoodId(zip: string): string | null {");
lines.push("  return zipToNeighborhoods[zip]?.[0] ?? null;");
lines.push("}");
lines.push('');
lines.push("export function getNeighborhoodIdsForZip(zip: string): string[] {");
lines.push("  return zipToNeighborhoods[zip] ?? [];");
lines.push("}");
lines.push('');
lines.push("export function getZipsForNeighborhoodId(id: string): string[] {");
lines.push("  return Object.entries(zipToNeighborhoods)");
lines.push("    .filter(([, ids]) => ids.includes(id))");
lines.push("    .map(([zip]) => zip);");
lines.push("}");

console.log(lines.join('\n'));
